### PR TITLE
[HIGH PRIORITY] Fix Integration Tests

### LINKED ISSUE #28: Add Tests for Elide Routes
Yahoo Elide routes all stuff, but we should add some integration tests, 
e.g. for permission ...

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41543123-add-tests-for-elide-routes?utm_campaign=plugin&utm_content=tracker%2F50822723&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F50822723&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #33: Integration Test for Clan Stuff
Currently Elide, JPA, Bean Validation is used heavily.
We should test this all in combination.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41555366-integration-test-for-clan-stuff?utm_campaign=plugin&utm_content=tracker%2F50822723&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F50822723&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by IDragonfire**
Fixes #33 
Fixes #28

### CODE REVIEW

**Comment by micheljung** [comment]
Where did you see a broke develop branch?

**Comment by IDragonfire** [comment]
Develop branch was fixed with https://github.com/FAForever/faf-java-api/commit/a6ea3b46e3dca2097759472e5bafa22fd3f075b9

File: src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java [hunk 1]
```diff
@@ -35,44 +29,25 @@
 import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
 import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
 
+
 @RunWith(SpringRunner.class)
 @SpringBootTest
-@Ignore("This needs to be cleaned up big time.")
+@Import(TestDatabase.class)
+@Transactional
 public class ClanControllerIntegrationTest {
```
Comment (micheljung) [inline src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java]: All integration tests will share a common test setup (including `@Transactional`) which is why there should be an `AbstractIntegrationTest` class.

File: src/test/java/com/faforever/integration/TestDatabase.java [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+import static org.junit.Assert.assertEquals;
+
+@Component
+@Getter
+public class TestDatabase {
+  private ClanRepository clanRepository;
+  private UserRepository userRepository;
+  private ClanMembershipRepository clanMembershipRepository;
+  private PlayerRepository playerRepository;
+  private OAuthClientRepository oAuthClientRepository;
```
Comment (micheljung) [inline src/test/java/com/faforever/integration/TestDatabase.java]: This is not the way to go, and repositories don't necessarily mean database access

File: src/test/java/com/faforever/integration/TestDatabase.java [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    assertEquals(0, clanMembershipRepository.count());
+  }
+
+  public void tearDown() {
+    clanMembershipRepository.deleteAll();
+    clanRepository.deleteAll();
+    userRepository.deleteAll();
+    oAuthClientRepository.deleteAll();
+    assertEmptyDatabase();
+  }
```
Comment (micheljung) [inline src/test/java/com/faforever/integration/TestDatabase.java]: The way to go is to run every test in a tansaction that rolls back after each test, no need to call deleteAll manually and do assertions that need to be maintained manually as well.

File: src/test/java/com/faforever/integration/factories/SessionFactory.java [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+import static junitx.framework.ComparableAssert.assertEquals;
+import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
+import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
+
+public class SessionFactory {
+
+  private static final String OAUTH_CLIENT_ID = "1234";
+  private static final String OAUTH_SECRET = "secret";
+
+  private static ObjectMapper objectMapper = new ObjectMapper();
```
Comment (micheljung) [inline src/test/java/com/faforever/integration/factories/SessionFactory.java]: Don't create a custom `ObjectMapper`, use the one provided as Spring Bean

File: src/test/java/com/faforever/integration/factories/SessionFactory.java [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+  private static ShaPasswordEncoder shaPasswordEncoder = new ShaPasswordEncoder(256);
+
+  @SneakyThrows
+  public static Session createUserAndGetAccessToken(TestDatabase database,
+                                                    MockMvc mvc) {
+    return createUserAndGetAccessToken("Dragonfire", "foo",
```
Comment (micheljung) [inline src/test/java/com/faforever/integration/factories/SessionFactory.java]: Certainly not `Dragonfire` :P

File: src/test/java/com/faforever/integration/factories/SessionFactory.java [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+        .setDefaultRedirectUri("test")
+        .setDefaultScope("test")
+        .setClientType(ClientType.PUBLIC);
+    database.getOAuthClientRepository().save(client);
+
+    long userCounter = database.getUserRepository().count();
+    User user = (User) new User()
+        .setPassword(shaPasswordEncoder.encodePassword(password, null))
+        .setLogin(login)
+        .setEmail(login + "@faforever.com");
```
Comment (micheljung) [inline src/test/java/com/faforever/integration/factories/SessionFactory.java]: Use `@example.com` to always make clear that it's test data

File: src/test/java/com/faforever/integration/factories/SessionFactory.java [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+    return new Session().setPlayer(player).setToken("Bearer " + token);
+  }
+
+
+  @Data
+  public static class Session {
+    private Player player;
+    private String Token;
+  }
+}
```
Comment (micheljung) [inline src/test/java/com/faforever/integration/factories/SessionFactory.java]: What's done in this class should be moved into the abstract integration test class and be non-static.

File: src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java [hunk 8]
```diff
@@ -81,205 +56,159 @@ public void setUp() {
...
-        me.getLogin());
+        session.getPlayer().getId(),
+        session.getPlayer().getLogin());
 
-    assertEquals(1, playerRepository.count());
+    assertEquals(1, database.getPlayerRepository().count());
     this.mvc.perform(get("/clans/me/")
-        .header("Authorization", accessToken))
+        .header("Authorization", session.getToken()))
         .andExpect(content().string(expected))
```
Comment (micheljung) [inline src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java]: String comparison is not a good idea; not only is it difficult to adjust, but we can't even rely on the order of the fields. There are frameworks for this case (as we already discussed). Spring MVC [seems to have this integrated already](https://www.petrikainulainen.net/programming/spring-framework/integration-testing-of-spring-mvc-applications-write-clean-assertions-with-jsonpath#writing-integration-tests).

File: src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java [hunk 9]
```diff
@@ -81,205 +56,159 @@ public void setUp() {
...
 
   @Test
   public void meDataWithClan() throws Exception {
-    String accessToken = createUserAndGetAccessToken("Dragonfire", "foo");
+    Session session = SessionFactory.createUserAndGetAccessToken(
+        database, mvc);
 
-    Clan clan = new Clan().setLeader(me).setTag("123").setName("abcClanName");
-    ClanMembership myMembership = new ClanMembership().setPlayer(me).setClan(clan);
+    Clan clan = new Clan().setLeader(session.getPlayer()).setTag("123").setName("abcClanName");
```
Comment (micheljung) [inline src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java]: Don't repeat method calls, extract them to variables.

File: src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java [hunk 10]
```diff
@@ -81,205 +56,159 @@ public void setUp() {
...
 
-    assertEquals(1, playerRepository.count());
-    assertEquals(1, clanRepository.count());
-    assertEquals(1, clanMembershipRepository.count());
+    assertEquals(1, database.getPlayerRepository().count());
+    assertEquals(1, database.getClanRepository().count());
+    assertEquals(1, database.getClanMembershipRepository().count());
     this.mvc.perform(get("/clans/me/")
-        .header("Authorization", accessToken))
+        .header("Authorization", session.getToken()))
```
Comment (micheljung) [inline src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java]: Instead of repeating this over and over again, I'm sure we can pull this into a super method.

File: src/test/java/com/faforever/api/data/JsonApiClanIntegrationTest.java [hunk 11]
```diff
@@ -88,146 +65,97 @@ public void setUp() {
...
-    clanMembershipRepository.deleteAll();
-    clanRepository.deleteAll();
-    userRepository.deleteAll();
-    oAuthClientRepository.deleteAll();
-    assertEquals(0, clanMembershipRepository.count());
-    assertEquals(0, clanRepository.count());
-    assertEquals(0, userRepository.count());
-    assertEquals(0, oAuthClientRepository.count());
+    // TODO: This is needed, because Elide has some problems with @Transactional annotation
+    database.tearDown();
```
Comment (micheljung) [inline src/test/java/com/faforever/api/data/JsonApiClanIntegrationTest.java]: Let's figure out what the problem is and fix it instead of working around it

File: src/test/java/com/faforever/integration/TestDatabase.java (hunk 3 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/integration/TestDatabase.java]: Not working in elide currently ...

File: src/test/java/com/faforever/integration/factories/SessionFactory.java (hunk 5 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/integration/factories/SessionFactory.java]: Why not?

File: src/test/java/com/faforever/integration/factories/SessionFactory.java (hunk 7 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/integration/factories/SessionFactory.java]: Some Tests may not need a session ...
I prefer composition over inheritance ....

File: src/test/java/com/faforever/integration/factories/SessionFactory.java (hunk 5 above)
Comment (micheljung) [inline src/test/java/com/faforever/integration/factories/SessionFactory.java]: Use something neutral, like `JUnit` to avoid potential confusion.

File: src/test/java/com/faforever/api/data/JsonApiClanIntegrationTest.java (hunk 11 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/api/data/JsonApiClanIntegrationTest.java]: Yes,  I (we?) will, but I will do it stepwise (iterative) and I know you don't like it, but I prefer sometimes working tests over no tests :p

I created an issue for this
https://github.com/FAForever/faf-java-api/issues/71

File: src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java (hunk 1 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java]: In the future, or is this required to get this merged?
I want not to touch your `AbstractIntegrationTest` implementation, because maybe you have a better way of doing it ...
Because `AbstractIntegrationTest` is not final and currently I  prefer composition over inheritance in this use case it's fine for me ...

But I aggree some real `basic` common subclass is essential for the future (next step):
https://github.com/FAForever/faf-java-api/issues/72

File: src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java (hunk 8 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java]: If I touch this we should adapt it everywhere:
https://github.com/FAForever/faf-java-api/issues/69

File: src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java (hunk 10 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/api/clan/ClanControllerIntegrationTest.java]: I though about this for while ....
It's hard because you have so many `versions` of super methods ...
In c# you can simply overload an existing method of an class ...

File: src/test/java/com/faforever/integration/TestDatabase.java (hunk 2 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/integration/TestDatabase.java]: This is needed to reduce the method parameters for all factories as long as https://github.com/FAForever/faf-java-api/issues/71 is not fixed ...
Otherwise the Factories can use `@Inject` to grab the repositories ...

File: src/test/java/com/faforever/integration/factories/SessionFactory.java (hunk 4 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/integration/factories/SessionFactory.java]: `No qualifying bean of type 'org.codehaus.jackson.map.ObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

File: src/test/java/com/faforever/integration/TestDatabase.java (hunk 2 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/integration/TestDatabase.java]: As long we need a manual cleanup we need one state manager who can reset all...

File: src/test/java/com/faforever/integration/TestDatabase.java (hunk 3 above)
Comment (IDragonfire) [inline src/test/java/com/faforever/integration/TestDatabase.java]: If you have another suggestion to fix https://github.com/FAForever/faf-java-api/issues/71 inform me... Currently we have to live with the manual `deleteAll`
