### PR TITLE
Closes #42 Use global exception handler

### LINKED ISSUE #42: Use global exception handler
http://www.baeldung.com/exception-handling-for-rest-with-spring#controlleradvice

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41756355-use-global-exception-handler?utm_campaign=plugin&utm_content=tracker%2F50822723&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F50822723&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by bukajsytlos**
Closes #42 Use global exception handler

- Error response format compatible with json-api standard
- customized spring security oauth error rendering

### CODE REVIEW

File: .editorconfig [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+[*]
+indent_style = space
+indent_size = 2
+end_of_line = lf
+charset = utf-8
+trim_trailing_whitespace = true
+insert_final_newline = true
+
+[*.md]
+trim_trailing_whitespace = false
```
Comment (IDragonfire) [inline .editorconfig]: This is from eclipse? We are all currently using InteliJ, great to see that eclipse is also working ...

File: src/main/java/com/faforever/api/config/GlobalControllerExceptionHandler.java [hunk 2]
```diff
@@ -4,44 +4,52 @@
...
-  public Map<String, Serializable> processValidationException(ValidationException ex) {
-    return errorResponse(ErrorCode.VALIDATION_FAILED.getTitle(), ex.getMessage());
+  public ErrorResponse processValidationException(ValidationException ex) {
+    return new ErrorResponse().addError(new ErrorResult(
+      HttpStatus.UNPROCESSABLE_ENTITY.value(),
+      ErrorCode.VALIDATION_FAILED.getCode(),
+      ErrorCode.VALIDATION_FAILED.getTitle(),
+      ex.getMessage(),
+      null
+    ));
```
Comment (IDragonfire) [inline src/main/java/com/faforever/api/config/GlobalControllerExceptionHandler.java]: If I remember correctly it was not possible to catch the global `ValidationException` or?
If yes we need a comment here ..

**Comment by IDragonfire** [comment]
I know I introduce

But I am not sure if this is working ..
https://coveralls.io/builds/11154453/source?filename=src%2Fmain%2Fjava%2Fcom%2Ffaforever%2Fapi%2Fconfig%2FGlobalControllerExceptionHandler.java#L24

I am sure I have some error tests 
@bukajsytlos did you test this?

From my view this PR can be merged and we create an seperate issue for this ...

File: .editorconfig (hunk 1 above)
Comment (micheljung) [inline .editorconfig]: http://editorconfig.org/

Comment (IDragonfire) [inline .editorconfig]: Good to know is @bukajsytlos using eclipse?
Because the Pr has no formatting issues from my view ^^
Great

Comment (micheljung) [inline .editorconfig]: He uses IntelliJ as well, but i guess he copied this file over from faf-java-server :)

File: src/main/java/com/faforever/api/clan/ClanService.java [hunk 3]
```diff
@@ -88,7 +91,7 @@ public String generatePlayerInvitationToken(Player requester, int newMemberId, i
     Clan clan = clanRepository.findOne(clanId);
 
     if (clan == null) {
-      throw new ApiException(new Error(ErrorCode.CLAN_NOT_EXISTS));
+      throw new ApiException(new Error(ErrorCode.CLAN_NOT_EXISTS, clanId));
```
Comment (micheljung) [inline src/main/java/com/faforever/api/clan/ClanService.java]: good catch

File: src/main/java/com/faforever/api/config/security/oauth2/JsonApiOauthMessageConverter.java [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+public class JsonApiOauthMessageConverter  extends MappingJackson2HttpMessageConverter {
+
+  @Override
+  protected void writeInternal(Object object, HttpOutputMessage outputMessage) throws IOException, HttpMessageNotWritableException {
+    super.writeInternal(transformObject(object), outputMessage);
+  }
+
+  protected Object transformObject(Object object) {
+    ErrorResponse response = new ErrorResponse();
+    if(object instanceof OAuth2Exception) {
```
Comment (micheljung) [inline src/main/java/com/faforever/api/config/security/oauth2/JsonApiOauthMessageConverter.java]: Please enable the following "Before Commit" actions in the commit dialog:
* Reformat Code
* Rearrange Code
* Optimize imports

thx :)

File: src/main/java/com/faforever/api/config/security/oauth2/OAuthResourceServerConfig.java [hunk 5]
```diff
@@ -34,16 +36,20 @@ public OAuthResourceServerConfig(FafApiProperties fafApiProperties, ResourceServ
 
   @Override
   public void configure(ResourceServerSecurityConfigurer resources) {
+    final OAuth2AuthenticationEntryPoint oAuth2AuthenticationEntryPoint = new OAuth2AuthenticationEntryPoint();
+    oAuth2AuthenticationEntryPoint.setExceptionRenderer(new JsonApiOauthExceptionRenderer());
     resources.resourceId(resourceId)
-        .tokenServices(tokenServices);
+      .tokenServices(tokenServices)
+      .authenticationEntryPoint(oAuth2AuthenticationEntryPoint)
+    ;
```
Comment (micheljung) [inline src/main/java/com/faforever/api/config/security/oauth2/OAuthResourceServerConfig.java]: Format error

File: .editorconfig (hunk 1 above)
Comment (bukajsytlos) [inline .editorconfig]: Yeah I am using IJ, but I noticed that some lines had 4spaces and some 2, so as Downlord pointed out, I just copied it from java-server. Is it ok?

File: src/main/java/com/faforever/api/config/GlobalControllerExceptionHandler.java (hunk 2 above)
Comment (bukajsytlos) [inline src/main/java/com/faforever/api/config/GlobalControllerExceptionHandler.java]: Honestly I just refactored it. I didnt analyze whether it is possible.
This PR was pushed mainly to get some feedback if I am going right direction since jsonapi standard, spring security, oauth is something new for me

File: src/main/java/com/faforever/api/config/error/ErrorResult.java [hunk 6]
```diff
@@ -1,9 +1,32 @@
...
 
 @Data
+@RequiredArgsConstructor
+@AllArgsConstructor
+@JsonInclude(JsonInclude.Include.NON_NULL)
 public class ErrorResult {
+  @JsonProperty("status")
+  private final Integer httpStatusCode;
+  @JsonProperty("code")
+  private Integer appCode;
```
Comment (bukajsytlos) [inline src/main/java/com/faforever/api/config/error/ErrorResult.java]: from the rest/jsonapi point of view I thought httpstatus is necessary, but since only our custom errors have appcode that those should be optional. Or do we want to group framework exceptions to some error codes?

File: .editorconfig (hunk 1 above)
Comment (micheljung) [inline .editorconfig]: Yes it is. Not sure how the 4 spaces made it into the code though, as the formatter settings are shared

File: src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java [hunk 7]
```diff
@@ -0,0 +1,107 @@
...
+import org.springframework.web.bind.annotation.ResponseBody;
+import org.springframework.web.bind.annotation.ResponseStatus;
+
+import javax.validation.ConstraintViolationException;
+import javax.validation.ValidationException;
+import java.text.MessageFormat;
+import java.util.Arrays;
+
+@ControllerAdvice
+// TODO implement a proper JSON-API error response
```
Comment (micheljung) [inline src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java]: Remove TODO

File: src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+  @ResponseStatus(HttpStatus.UNPROCESSABLE_ENTITY)
+  @ResponseBody
+  public ErrorResponse processValidationException(ConstraintViolationException ex) {
+    final ErrorResponse errorResponse = new ErrorResponse();
+    ex.getConstraintViolations().forEach(constraintViolation -> {
+      errorResponse.addError(new ErrorResult(
+        String.valueOf(HttpStatus.UNPROCESSABLE_ENTITY.value()),
+        String.valueOf(ErrorCode.VALIDATION_FAILED.getCode()),
+        ErrorCode.VALIDATION_FAILED.getTitle(),
+        constraintViolation.getPropertyPath().toString() + " " + constraintViolation.getMessage(),
```
Comment (micheljung) [inline src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java]: Call to `toString()` is not needed since it's a string concatenation (I think IntelliJ highlights this).
Also, I usually prefer `String.format()` over concatenation, and the format `%s: %s`.

File: src/main/java/com/faforever/api/error/ErrorResult.java [hunk 9]
```diff
@@ -0,0 +1,39 @@
...
+  private final String title;
+  private final String detail;
+  private Meta meta;
+
+  @Data
+  @RequiredArgsConstructor
+  @AllArgsConstructor
+  @JsonInclude(JsonInclude.Include.NON_NULL)
+  public static class Meta {
+    private String[] args;
```
Comment (micheljung) [inline src/main/java/com/faforever/api/error/ErrorResult.java]: An argument may also be an integer, so `args` can be `Object[]`. Then you don't need the `getArgsAsStrings().

File: src/main/java/com/faforever/api/error/ErrorResult.java [hunk 10]
```diff
@@ -0,0 +1,39 @@
...
+    private Map<String, String> additionalInfo;
+  }
+
+  public static Meta createMeta(String[] args, Map<String, String> additionalInfo) {
```
Comment (micheljung) [inline src/main/java/com/faforever/api/error/ErrorResult.java]: Since it may be unexpected that a `create` method may return null, either annotate it with `@NotNull` (from `org.jetbrains.annotations`), or return an `Optional<Meta>` (I think this is to be preferred). The caller can then use `.orElseGet(null)`

File: src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java [hunk 11]
```diff
@@ -0,0 +1,107 @@
...
+
+  @ExceptionHandler(ProgrammingError.class)
+  @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
+  @ResponseBody
+  public ErrorResponse processApiException(ProgrammingError ex) {
+
+    ErrorResponse response = new ErrorResponse();
+    response.addError(new ErrorResult(
+      String.valueOf(HttpStatus.INTERNAL_SERVER_ERROR.value()),
+      ex.getMessage(),
```
Comment (micheljung) [inline src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java]: I'd use `Internal Server Error` as a title here.

File: src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java [hunk 12]
```diff
@@ -0,0 +1,107 @@
...
+      ex.getMessage()
+    ));
+    return response;
+  }
+
+  @ExceptionHandler(Exception.class)
+  @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
+  @ResponseBody
+  public ErrorResponse processApiException(Exception ex) {
+
```
Comment (micheljung) [inline src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java]: Remove those empty lines to keep the code consistent :)

File: src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java [hunk 13]
```diff
@@ -0,0 +1,107 @@
...
+    if (ex instanceof InsufficientAuthenticationException) {
+      throw (InsufficientAuthenticationException) ex;
+    }
+    ErrorResponse response = new ErrorResponse();
```
Comment (micheljung) [inline src/main/java/com/faforever/api/error/GlobalControllerExceptionHandler.java]: Rather insert it above this line
